name: Build mathybperf

on:
  # Push to master or PR
  push:
    branches:
      - main
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Scheduled build at 0230 UTC on Monday mornings to detect bitrot.
    - cron:  '30 2 * * 1'

jobs:
  build:
    name: "Build mathybperf"  
    # The type of runner that the job will run on
    runs-on: self-hosted
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla:latest
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd ..
          rm -rf build
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Update Firedrake
        run: |
          . /home/firedrake/firedrake/bin/activate
          firedrake-update
      - name: Switch Firedrake branches
        run: |
          . /home/firedrake/firedrake/bin/activate
          git -C /home/firedrake/firedrake/src/firedrake/ checkout sv/local-matfree-pr
          git -C /home/firedrake/firedrake/src/tsfc/ checkout sv/local-matfree-pr
          git -C /home/firedrake/firedrake/src/PyOP2/ checkout sv/local-matfree-pr
      - name: Install mathybperf and extra dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pip install pandas
          python -m pip install flake8 pylint
          python -m pip install -e ./
      - name: Test mathybperf
        run: |
          . /home/firedrake/firedrake/bin/activate
          python $(which firedrake-clean)
          export PYOP2_DEBUG=1
          python -m pytest -v mathybperf/tests
      # - name: Test Slate
      #   run: |
      #     . /home/firedrake/firedrake/bin/activate
      #     python $(which firedrake-clean)
      #     python -m pytest -n 12 -v /home/firedrake/firedrake/src/firedrake/tests/slate
      - name: Lint
        if: ${{ always() }}
        run: |
          . /home/firedrake/firedrake/bin/activate
          make lint